version: '3.1'
services:
  database:
    image: postgres
    restart: always
    container_name: postgres_db
    ports:
      - 5432:5432
    env_file:
      - .env

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379